Move repos to thoth station team
AICoE/common pull request #23
Opened 2021-09-06 08:53 UTC by pacospace

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

2021-09-06 08:56 UTC, goern requested changes

2021-09-06 08:56 UTC, goern commented on github-config.yaml
> -          manage-dependencies-tutorial: admin
@pacospace please dont remove them from the SourceOps team, as the bots still need to be maintainers, as the assist us humans.

2021-09-06 09:03 UTC, goern commented
/approve

2021-09-28 16:09 UTC, goern commented
/test all

2021-09-28 16:09 UTC, goern commented
/lgtm
/approve

2021-09-28 16:10 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/common/pull/23#issuecomment-929372347" title="Approved">goern</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fcommon).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/common/blob/main/OWNERS)~~ [goern]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-28 16:10 UTC, sesheta commented
@pacospace: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 018cfcddf35e29c0be9c7d1e33650849ccb83863 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_common/23/pre-commit/1442884190327541760) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=common&pr=23). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Apacospace). Please help us and [open an issue](https://github.com/AICoE/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-01 11:38 UTC, goern commented
/assign @pacospace

2021-10-01 12:10 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-10-01 12:10 UTC, pacospace commented
> /assign @pacospace

updated! Thanks!

2021-10-04 07:26 UTC, goern commented
/lgtm

2021-10-04 07:40 UTC, merged