updating the urls for pre-commit
AICoE/common pull request #41
Opened 2021-11-11 16:46 UTC by Gregory-Pereira

Related to [github security protocol update](https://github.blog/2021-09-01-improving-git-protocol-security-github/#dropping-insecure-signature-algorithms)

Partially addresses [pre-commit fails due to the URL](https://github.com/thoth-station/thoth-application/issues/2111) in thoth station, but for aicoe-common.

2021-11-11 16:47 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fcommon).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/common/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2021-11-11 16:47 UTC, sesheta commented
Hi @Gregory-Pereira. Thanks for your PR.

I'm waiting for a [AICoE](https://github.com/orgs/AICoE/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/AICoE/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fcommon).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-12 16:52 UTC, harshad16 requested changes
please do the following changes

2021-11-12 16:52 UTC, harshad16 commented on .pre-commit-config.yaml
> +  - repo: https//github.com/Lucas-C/pre-commit-hooks
`:` is missing , please fix it 
```suggestion
  - repo: https://github.com/Lucas-C/pre-commit-hooks
```

2021-11-12 16:52 UTC, harshad16 commented on .pre-commit-config.yaml
> +  - repo: https//github.com/pre-commit/pre-commit-hooks
```suggestion
  - repo: https://github.com/pre-commit/pre-commit-hooks
```

2021-11-17 14:15 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/common/pull/41#pullrequestreview-808646225" title="Approved">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fcommon).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/common/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2021-12-15 16:11 UTC, codificat commented
/lgtm
/retest

2022-02-04 23:59 UTC, Gregory-Pereira commented
/assign @tumido take a look when you can

2022-02-09 21:35 UTC, Gregory-Pereira commented
bump @tumido, /cc @goern

2022-02-17 01:08 UTC, Gregory-Pereira commented
/assign @goern

2022-02-28 16:55 UTC, codificat commented
/ok-to-test

2022-02-28 19:33 UTC, codificat commented
/unassign
I am not an approver here

bump @goern @tumido

2022-03-02 13:16 UTC, goern commented
/approve

2022-03-02 13:22 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/common/pull/41#issuecomment-1056920434" title="Approved">goern</a>*, *<a href="https://github.com/AICoE/common/pull/41#pullrequestreview-808646225" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fcommon).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/common/blob/main/OWNERS)~~ [goern]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-02 14:08 UTC, merged